# import linecache
#
# filename = 'input_subs.txt'
#
# s = linecache.getline(filename, 1)
# t = linecache.getline(filename, 2)

s = "GAGGTAACCGCAAGCCATTCAACCGCAAACCGCAAACCGCACCAACCGCAAACCGCACTCGAACCGCAAACCGCAATAACCGCAAACCGCAAACCGCAAACCGCAAAACCGCAAACCGCAGATACAACCGCACAACCGCAAACCGCAAAACCGCAACCAGTTAACCGCAAACCGCATTAACCGCAAGAAACCGCACGAACCGCATGTCCAACCGCAGCGAACCGCATGGAACCGCAAGTGAACCGCAAACCGCAAACCGCAACAGCAACCGCAAACCGCACAAACCGCAGAACCGCAAAACCGCATCAACCGCAAACCGCAATAACCGCAAAAACCGCAAACCGCAGAGGTCATGAACCGCAAACCGCAACAACCGCAGTAACCGCACGTAACCGCAAACCGCAGAACCGCACTAGAACCGCACTAACCGCAATCATAACCGCAAACCGCAGAACCGCACGAAACCAGAACCGCACGAACCGCAGGAGTCAACCGCAAACCGCACTAAACCGCAAACCGCAAACCGCATGGACAACCGCACAGAACCGCATTTGTAACCGCAAACCGCATAACCGCAACTTTTTGGATAAAAGAAAACCGCAGTAAACCGCAAACCGCATAACCGCAGTGGAACCGCATTCCAACCGCAATCTAACCGCAAACCGCAAACCGCAAACCGCAAACAACCGCACAACCGCAGAGCCAACCGCAAAAACCGCAAACCGCAAACCGCAAGAACCGCAAACCGCATCAACCGCATAAACCGCAAACCGCATGAACCGCATATAGAAACCGCAAACCGCATTCAACCGCA"
t = "AACCGCAAA"

positions = []
index = 0
go = True
while go:
    index = s.find(t, index)
    if index == -1:
        go = False
    else:
        index += 1
        positions.append(index)

#print(str(positions))

for i in positions:
    print(i, end=' ')
